version: "2.1"
services:
  divolte-kafka:
    image: krisgeus/docker-kafka
    container_name: divolte-kafka
    environment:
      - ADVERTISED_HOST=divolte-kafka
      - LOG_RETENTION_HOURS=1
      - AUTO_CREATE_TOPICS=false
      - KAFKA_CREATE_TOPICS=divolte:4:1
    ports:
      - 9092:9092
      - 2181:2181
  docker-divolte:
    image: krisgeus/docker-divolte
    container_name: docker-divolte
    environment:
      - DIVOLTE_KAFKA_BROKER_LIST=divolte-kafka:9092
    ports:
      - 8290:8290
    depends_on:
      - divolte-kafka
    links:
      - divolte-kafka:divolte-kafka
